"""Normalize complete GHCNh yearly PSV files into provenance-carrying observations."""
from __future__ import annotations

import argparse
import csv
import hashlib
from datetime import datetime, timezone
from pathlib import Path

OUT_COLS = ["station", "station_name", "valid_utc", "latitude", "longitude",
            "elevation_m", "temperature_f", "dewpoint_f", "temperature_quality_code",
            "temperature_report_type", "raw_path", "sha256", "source_receipt_time"]


def _float(value: str) -> float | None:
    if not value or value in {"MM", "M", "NA"}:
        return None
    try:
        return float(value)
    except ValueError:
        return None


def parse_file(path: Path, source_receipt_time: str = "") -> tuple[list[dict], int]:
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    rows: list[dict] = []
    rejected = 0
    with path.open(newline="", encoding="utf-8", errors="replace") as handle:
        reader = csv.DictReader(handle, delimiter="|")
        required = {"STATION", "Station_name", "DATE", "LATITUDE", "LONGITUDE", "ELEVATION", "temperature", "dew_point_temperature"}
        if not required.issubset(reader.fieldnames or set()):
            raise ValueError(f"{path} lacks required GHCNh columns")
        for raw in reader:
            try:
                valid = datetime.fromisoformat(raw["DATE"].replace("Z", "+00:00"))
                if valid.tzinfo is None:
                    valid = valid.replace(tzinfo=timezone.utc)
                valid_utc = valid.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")
            except (KeyError, ValueError):
                rejected += 1
                continue
            temperature_c = _float(raw.get("temperature", ""))
            dewpoint_c = _float(raw.get("dew_point_temperature", ""))
            if temperature_c is None:
                rejected += 1
                continue
            rows.append({
                "station": raw["STATION"], "station_name": raw["Station_name"],
                "valid_utc": valid_utc, "latitude": raw["LATITUDE"],
                "longitude": raw["LONGITUDE"], "elevation_m": raw["ELEVATION"],
                "temperature_f": round(temperature_c * 9 / 5 + 32, 3),
                "dewpoint_f": "" if dewpoint_c is None else round(dewpoint_c * 9 / 5 + 32, 3),
                "temperature_quality_code": raw.get("temperature_Quality_Code", ""),
                "temperature_report_type": raw.get("temperature_Report_Type", ""),
                "raw_path": str(path), "sha256": digest,
                "source_receipt_time": source_receipt_time,
            })
    return rows, rejected


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--rejections", type=Path, required=True)
    args = parser.parse_args()
    rows: list[dict] = []
    rejects = []
    # Accept either a single year directory or the parent ``by_year`` tree.
    # Recursive discovery lets adjacent complete years be merged without
    # overwriting earlier normalized observations.
    for path in sorted(args.input.rglob("GHCNh_*_*.psv")):
        receipt = ""
        manifest = path.parent / "manifest.json"
        if manifest.exists():
            try:
                import json
                entries = json.loads(manifest.read_text()).get("rows", [])
                receipt = next((r.get("retrieved_at_utc", "") for r in entries if r.get("raw_path") == str(path)), "")
            except (OSError, ValueError, TypeError):
                receipt = ""
        # Integrity manifests generated by the inventory utility may omit the
        # collector clock; the immutable file mtime is the local acquisition
        # receipt fallback and is retained explicitly in normalized output.
        if not receipt:
            try:
                receipt = datetime.fromtimestamp(path.stat().st_mtime, timezone.utc).isoformat().replace("+00:00", "Z")
            except OSError:
                receipt = ""
        parsed, rejected = parse_file(path, receipt)
        rows.extend(parsed)
        rejects.append({"raw_path": str(path), "rejected_rows": rejected})
    rows.sort(key=lambda row: (row["station"], row["valid_utc"]))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=OUT_COLS)
        writer.writeheader(); writer.writerows(rows)
    args.rejections.write_text("raw_path,rejected_rows\n" + "\n".join(f"{r['raw_path']},{r['rejected_rows']}" for r in rejects) + "\n")
    print(f"wrote {args.output} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
